name: Cypress Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          # Headless mod için ENV değişkeni kullanın
          env: CYPRESS_HEADLESS=true
